#############################################
# LIFEsim 2 Configuration File
# -------------------------------------------
# For documentation see:
# https://github.com/pahuber/LIFEsim2
#############################################
---
# -------------------------------------------
# Simulation Configuration
# -------------------------------------------
simulation:
  grid_size: 80
  time_step: 10 min
# -------------------------------------------
# Observation Configuration
# -------------------------------------------
observation:
  adjust_baseline_to_habitable_zone: true
  integration_time: 1 d
  optimized_wavelength: 10 um
# -------------------------------------------
# Observatory Configuration
# -------------------------------------------
observatory:
  array_configuration:
    type: emma-x-circular-rotation
    baseline_maximum: 600 m
    baseline_minimum: 8 m
    baseline_ratio: 6
    modulation_period: 1 d
  beam_combination_scheme: double-bracewell
  instrument_parameters:
    aperture_diameter: 4 m
    wavelength_range_lower_limit: 4 um
    wavelength_range_upper_limit: 18 um
    spectral_resolving_power: 20
# -------------------------------------------
# Noise Configuration
# -------------------------------------------
noise:
  stellar_leakage: true
  local_zodi: true
  exozodi: true
  exozodi_level: 3
  fiber_injection_variability: true
  optical_path_difference_variability: true
...
