#############################################
# SYGN Configuration File
# -------------------------------------------
# For documentation see:
# https://github.com/pahuber/SYGN
############################################
---
# -------------------------------------------
# Settings
# -------------------------------------------
settings:
  grid_size: 60
  time_steps: 100
  planet_orbital_motion: false
  noise:
    stellar_leakage: true
    local_zodi_leakage: false
    exozodi_leakage: false
    amplitude_perturbations: true
    phase_perturbations:
      apply: true
      power_law_exponent: 1
      rms: 0.1 nm
    polarization_perturbations:
      apply: true
      power_law_exponent: 1
      rms: 0.1 rad

# -------------------------------------------
# Mission Configuration
# -------------------------------------------
mission:
  integration_time: 1 d
  modulation_period: 1 d
  baseline_ratio: 6
  baseline_maximum: 600 m
  baseline_minimum: 5 m
  optimized_differential_output: 0
  optimized_star_separation: habitable-zone
  optimized_wavelength: 10 um
# -------------------------------------------
# Observatory Configuration
# -------------------------------------------
observatory:
  array_configuration: emma-x-circular-rotation
  beam_combination_scheme: double-bracewell
  instrument_parameters:
    aperture_diameter: 4 m
    spectral_resolving_power: 30
    wavelength_range_lower_limit: 4 um
    wavelength_range_upper_limit: 18 um
    unperturbed_instrument_throughput: 0.1
...
