#############################################
# LIFEsim 2 Configuration File
# -------------------------------------------
# For documentation see:
# https://github.com/pahuber/LIFEsim2
#############################################
---
# -------------------------------------------
# Simulation Configuration
# -------------------------------------------
simulation:
  grid_size: 80
  time_step: 5 min
  noise_contributions:
    stellar_leakage: true
    local_zodi_leakage: false
    exozodi_leakage: false
    fiber_injection_variability: true
    optical_path_difference_variability:
      apply: true
      power_law_exponent: 1
      rms: 0.1 nm
# -------------------------------------------
# Observation Configuration
# -------------------------------------------
observation:
  adjust_baseline_to_habitable_zone: true
  integration_time: 10 h
  optimized_wavelength: 10 um
# -------------------------------------------
# Observatory Configuration
# -------------------------------------------
observatory:
  array_configuration:
    type: emma-x-circular-rotation
    baseline_maximum: 600 m
    baseline_minimum: 8 m
    baseline_ratio: 6
    modulation_period: 10 h
  beam_combination_scheme: double-bracewell
  instrument_parameters:
    aperture_diameter: 4 m
    spectral_resolving_power: 20
    wavelength_range_lower_limit: 4 um
    wavelength_range_upper_limit: 18 um
    unperturbed_instrument_throughput: 0.1
...
